version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - manga_network
    ports:
      - '27017:27017'
    volumes:
      - ./mongod.conf.orig:/etc/mongod.conf.orig
      - ${MONGODB_DB_STORAGE_PATH}:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

networks:
  manga_network:
    driver: bridge