version: '3'

services:
  redis:
    image: "redis:latest"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - ${RABBITMQ_STORAGE_PATH}:/data
networks:
  manga_network:
    driver: bridge